//
//  GameConfig.h
//  CircleGame
//
//  Created by Joanne Dyer on 1/19/13.
//
//

#ifndef GameConfig_h
#define GameConfig_h

//main game area positions.
#define GAME_AREA_X_COORD 10
#define GAME_AREA_Y_COORD 37
#define SQUARE_SIDE_LENGTH 43
#define NUMBER_OF_ROWS 9
#define NUMBER_OF_COLUMNS 7

//header positions.
#define HEADER_X_COORD 0
#define HEADER_Y_COORD 432
#define COUNTDOWN_BAR_X_COORD 10
#define COUNTDOWN_BAR_Y_COORD 436
#define PAUSE_X_COORD 270
#define PAUSE_Y_COORD 438

//footer positions.
#define FOOTER_X_COORD 0
#define FOOTER_Y_COORD 2
#define LEVEL_X_COORD 205
#define LEVEL_Y_COORD 5
#define LEVEL_WIDTH 60
#define LEVEL_HEIGHT 25
#define TIME_LABEL_OFFSET 70
#define TIME_WIDTH 25
#define TIME_HEIGHT 25

#define MAX_RADIUS 25
#define MIN_RADIUS 20.0
#define LOW_COUNTDOWN_PERCENTAGE 10
#define MAX_VALUE_COUNTDOWN 6000//30 TEMP trying out infinite values.
#define MIN_VALUE_COUNTDOWN 6000//25 TEMP trying out infinite values.
#define MAX_REFRESH_COUNTDOWN 15//13
#define MIN_REFRESH_COUNTDOWN 12//10
#define MAX_SPAWN_COUNTDOWN 13
#define MIN_SPAWN_COUNTDOWN 10
//#define INITIAL_SPAWN_COUNTDOWN 9
//#define SPAWN_COUNTDOWN_DECREASE
//#define MAX_COOLDOWN 20 //16
#define MIN_COOLDOWN 7
#define INITIAL_MAX_COOLDOWN 15
#define MAX_COOLDOWN_INCREASE 2 
#define CHARGE_TIME 0//0.5
#define NUMBER_OF_SEGMENTS 45
#define SPEED_UP_THRESHOLD 0.5
#define CRITICAL_THRESHOLD 0.2 //proportion
#define INNER_CIRCLE_OPACITY 255
#define OUTER_CIRCLE_OPACITY 150
#define OPAQUE 255
#define TRANSPARENT 0
#define HIGH_VALUE_PERCENTAGE 10
#define MEDIUM_VALUE_PERCENTAGE 30
//#define NOTIFICATION_NEW_VALUE_LIGHT_NEEDED @"NewValueLightNeededNotification"
#define NEW_VALUE_DELAY_IN_SECONDS 1.5
#define SPEED_IN_POINTS_PER_SECOND 120.0
#define PERCENTAGE_OF_LIGHTS_START_ON_COOLDOWN 25
#define INITIAL_COUNTDOWN_SPEED_IN_PERCENTAGE_PER_SECOND 5.0
#define LEVEL_1_TO_5_COUNTDOWN_SPEED_INCREASE 0.5
#define LEVEL_6_TO_10_COUNTDOWN_SPEED_INCREASE 0.2
#define LEVEL_11_TO_20_COUNTDOWN_SPEED_INCREASE 0.1
#define LEVEL_21_ONWARDS_COUNTDOWN_SPEED_INCREASE 0.05
#define COUNTDOWN_SPEED_RATE_OF_CHANGE 0.005
#define COUNTDOWN_HIGH_INCREASE_PERCENTAGE 48.0
#define COUNTDOWN_MEDIUM_INCREASE_PERCENTAGE 36.0
#define COUNTDOWN_LOW_INCREASE_PERCENTAGE 24.0
//#define COUNTDOWN_BAR_OPACITY 150
#define LEVEL_LENGTH_IN_SECONDS 30//60
#define GAME_LAYER_TAG 1

#endif
