//
//  GameConfig.h
//  CircleGame
//
//  Created by Joanne Dyer on 1/19/13.
//
//

#ifndef GameConfig_h
#define GameConfig_h

//TODO Radius should be determined by size of screen.
#define GAME_AREA_X_COORD 0
#define GAME_AREA_Y_COORD 0
#define GAME_AREA_HEIGHT 427
#define GAME_AREA_WIDTH  320
#define COUNTDOWN_BAR_X_COORD 15
#define COUNTDOWN_BAR_Y_COORD 430
#define NUMBER_OF_ROWS 8
#define NUMBER_OF_COLUMNS 6
#define MAX_RADIUS 25
#define MIN_RADIUS 16.0
#define LOW_COUNTDOWN_PERCENTAGE 10
#define LOW_MAX_COUNTDOWN 15
#define LOW_MIN_COUNTDOWN 10
#define HIGH_MAX_COUNTDOWN 20
#define HIGH_MIN_COUNTDOWN 15
#define MAX_COOLDOWN 20
#define MIN_COOLDOWN 15
#define NUMBER_OF_SEGMENTS 45
#define CRITICAL_THRESHOLD 0.2 //proportion
#define INNER_CIRCLE_OPACITY 255
#define OUTER_CIRCLE_OPACITY 150
#define OPAQUE 255
#define TRANSPARENT 0
#define HIGH_VALUE_PERCENTAGE 10
#define MEDIUM_VALUE_PERCENTAGE 20
#define NOTIFICATION_LIGHT_ON_COOLDOWN @"LightOnCooldownNotification"
#define SPEED_IN_POINTS_PER_SECOND 120.0
#define PERCENTAGE_OF_LIGHTS_START_ON_COOLDOWN 50
#define COUNTDOWN_SPEED_IN_PERCENTAGE_PER_SECOND 8.0
#define COUNTDOWN_HIGH_INCREASE_PERCENTAGE 50.0
#define COUNTDOWN_BAR_OPACITY 150

#endif
