//
//  GameConfig.h
//  CircleGame
//
//  Created by Joanne Dyer on 1/19/13.
//
//

#ifndef GameConfig_h
#define GameConfig_h

//main game area positions.
#define GAME_AREA_X_COORD 10
#define GAME_AREA_Y_COORD 37
#define SQUARE_SIDE_LENGTH 43
#define NUMBER_OF_ROWS 9
#define NUMBER_OF_COLUMNS 7

//header positions.
#define HEADER_X_COORD 0
#define HEADER_Y_COORD 432
#define COUNTDOWN_BAR_X_COORD 10
#define COUNTDOWN_BAR_Y_COORD 436
#define PAUSE_X_COORD 270
#define PAUSE_Y_COORD 438

//footer positions.
#define FOOTER_X_COORD 0
#define FOOTER_Y_COORD 2
#define LEVEL_X_COORD 20
#define LEVEL_Y_COORD 3
#define LEVEL_WIDTH 105
#define LEVEL_HEIGHT 25
//#define TIME_LABEL_OFFSET 70
//#define TIME_WIDTH 25
//#define TIME_HEIGHT 25
#define SCORE_X_COORD 185
#define SCORE_Y_COORD 3
#define SCORE_WIDTH 135
#define SCORE_HEIGHT 25
#define STAR_SPRITE_X_COORD 125
#define STAR_SPRITE_Y_COORD 17
#define STARS_REMAINING_X_COORD 135
#define STARS_REMAINING_Y_COORD 3
#define STARS_REMAINING_WIDTH 40
#define STARS_REMAINING_HEIGHT 25

#define MAX_RADIUS 25
#define MIN_RADIUS 20.0
#define LOW_COUNTDOWN_PERCENTAGE 10
#define MAX_VALUE_COUNTDOWN 6000//30 TEMP trying out infinite values.
#define MIN_VALUE_COUNTDOWN 6000//25 TEMP trying out infinite values.
#define MAX_REFRESH_COUNTDOWN 14//15
#define MIN_REFRESH_COUNTDOWN 11//12
#define MAX_SPAWN_COUNTDOWN 13
#define MIN_SPAWN_COUNTDOWN 10
#define NUMBER_OF_LEVELS_FOR_COUNTDOWN_REDUCTION 5
#define MAX_COUNTDOWN_REDUCTION 5
//#define INITIAL_SPAWN_COUNTDOWN 9
//#define SPAWN_COUNTDOWN_DECREASE
//#define MAX_COOLDOWN 20 //16
#define MIN_COOLDOWN 7
#define INITIAL_MAX_COOLDOWN 30//15
#define MAX_COOLDOWN_INCREASE 0.5
#define CHARGE_TIME 0//0.5
#define NUMBER_OF_SEGMENTS 45
#define SPEED_UP_THRESHOLD 0.5
#define CRITICAL_THRESHOLD 0.1 //proportion
#define MENU_CRITICAL_THRESHOLD 0.2
#define INNER_CIRCLE_OPACITY 255
#define OUTER_CIRCLE_OPACITY 150
#define OPAQUE 255
#define TRANSPARENT 0
#define HIGH_VALUE_PERCENTAGE 10
#define MEDIUM_VALUE_PERCENTAGE 30
//#define NOTIFICATION_NEW_VALUE_LIGHT_NEEDED @"NewValueLightNeededNotification"
#define NEW_VALUE_DELAY_IN_SECONDS 1.5
#define SPEED_IN_POINTS_PER_SECOND 150.0//120.0
#define PERCENTAGE_OF_LIGHTS_START_ON_COOLDOWN 25
#define INITIAL_COUNTDOWN_SPEED_IN_PERCENTAGE_PER_SECOND 5.0
#define LEVEL_1_TO_5_COUNTDOWN_SPEED_INCREASE 0.7//0.5
#define LEVEL_6_TO_10_COUNTDOWN_SPEED_INCREASE 0.3//0.2
#define LEVEL_11_TO_20_COUNTDOWN_SPEED_INCREASE 0.2//0.1
#define LEVEL_21_ONWARDS_COUNTDOWN_SPEED_INCREASE 0.1//0.05
#define COUNTDOWN_SPEED_RATE_OF_CHANGE 0.005
#define COUNTDOWN_HIGH_INCREASE_PERCENTAGE 48.0
#define COUNTDOWN_MEDIUM_INCREASE_PERCENTAGE 36.0
#define COUNTDOWN_LOW_INCREASE_PERCENTAGE 24.0
#define SCORE_FOR_HIGH_VALUE 375
#define SCORE_FOR_MEDIUM_VALUE 250
#define SCORE_FOR_LOW_VALUE 125
//#define COUNTDOWN_BAR_OPACITY 150
//#define LEVEL_LENGTH_IN_SECONDS 30//60
#define STARS_TO_LEVEL_UP 10
#define GAME_LAYER_TAG 1
#define COUNTDOWN_BAR_GLOW_TIME 1.0
#define COUNTDOWN_WARNING_START_PERCENTAGE 30.0
#define COUNTDOWN_BAR_WARNING_FLASH_TIME 1.0

#define MAX_LEVEL 999
#define MAX_SCORE 999999

#define SOUND_EFFECTS_ON_KEY @"soundEffectsOnKey"
#define MUSIC_ON_KEY @"musicOnKey"
#define SOUND_EFFECTS_VOLUME 0.25f
#define MUSIC_VOLUME 0.2f

#define HIGH_SCORE_CATEGORY @"blah" //TODO

#endif
