//
//  GameConfig.h
//  CircleGame
//
//  Created by Joanne Dyer on 1/19/13.
//
//

#ifndef GameConfig_h
#define GameConfig_h

//GAME POSITIONS
//main game area positions.
#define GAME_AREA_X_COORD 10
#define GAME_AREA_Y_COORD 37
#define SQUARE_SIDE_LENGTH 43
#define NUMBER_OF_ROWS 9
#define NUMBER_OF_COLUMNS 7
//header positions.
#define HEADER_X_COORD 0
#define HEADER_Y_COORD 432
#define COUNTDOWN_BAR_X_COORD 10
#define COUNTDOWN_BAR_Y_COORD 436
#define PAUSE_X_COORD 270
#define PAUSE_Y_COORD 438
//footer positions.
#define FOOTER_X_COORD 0
#define FOOTER_Y_COORD 2
#define LEVEL_X_COORD 20
#define LEVEL_Y_COORD 3
#define LEVEL_WIDTH 105
#define LEVEL_HEIGHT 25
#define SCORE_X_COORD 185
#define SCORE_Y_COORD 3
#define SCORE_WIDTH 135
#define SCORE_HEIGHT 25
#define STAR_SPRITE_X_COORD 125
#define STAR_SPRITE_Y_COORD 17
#define STARS_REMAINING_X_COORD 135
#define STARS_REMAINING_Y_COORD 3
#define STARS_REMAINING_WIDTH 40
#define STARS_REMAINING_HEIGHT 25

//MENUS
//intro
#define INTRO_TRANSITION_TIME 1.0
//main menu
#define LOGO_X_COORD 160
#define LOGO_Y_COORD 347
#define MAIN_MENU_MENU_X_COORD 160
#define MAIN_MENU_MENU_Y_COORD 190
//about
#define ABOUT_TITLE_X_COORD 160
#define ABOUT_TITLE_Y_COORD 340
#define ABOUT_MENU_X_COORD 160
#define ABOUT_MENU_Y_COORD 218
//settings
#define SETTINGS_TITLE_X_COORD 160
#define SETTINGS_TITLE_Y_COORD 330
#define SOUND_EFFECTS_TITLE_X_COORD 160
#define SOUND_EFFECTS_TITLE_Y_COORD 275
#define SOUND_EFFECTS_TOGGLE_X_COORD 160
#define SOUND_EFFECTS_TOGGLE_Y_COORD 240
#define MUSIC_TITLE_X_COORD 160
#define MUSIC_TITLE_Y_COORD 195
#define MUSIC_TOGGLE_X_COORD 160
#define MUSIC_TOGGLE_Y_COORD 160
//credits
#define LICENSE_X_COORD 158
#define LICENSE_Y_COORD 182
//general
#define MENU_PADDING 10.0
#define MENU_TRANSITION_TIME 0.6
#define BACK_X_COORD 76
#define BACK_Y_COORD 51
#define NEXT_X_COORD 250
#define NEXT_Y_COORD 51
#define MENU_CRITICAL_THRESHOLD 0.2

//LIGHTS
//setup
#define PERCENTAGE_OF_LIGHTS_START_ON_COOLDOWN 25
#define PERCENTAGE_OF_LIGHTS_START_ON_MAX_COUNTDOWN 10
//animation
#define MAX_RADIUS 25
#define MIN_RADIUS 20.0
#define SPEED_UP_THRESHOLD 0.5
#define CRITICAL_THRESHOLD 0.1
#define OUTER_CIRCLE_OPACITY 150
//timers
#define MAX_REFRESH_COUNTDOWN 14
#define MIN_REFRESH_COUNTDOWN 11
#define MAX_SPAWN_COUNTDOWN 13
#define MIN_SPAWN_COUNTDOWN 10
#define INITIAL_COUNTDOWN_REDUCTION 0
#define COUNTDOWN_REDUCTION_PER_LEVEL 0.2
#define MAX_COUNTDOWN_REDUCTION 5
#define MIN_COOLDOWN 7
#define INITIAL_MAX_COOLDOWN 30
#define MAX_COOLDOWN_INCREASE 0.5
#define CHARGE_TIME 0
#define NEW_VALUE_DELAY_IN_SECONDS 1.5

//PLAYER
#define SPEED_IN_POINTS_PER_SECOND 150.0

//COUNTDOWN
//speeds
#define INITIAL_COUNTDOWN_SPEED_IN_PERCENTAGE_PER_SECOND 4.0
#define LEVEL_1_TO_5_COUNTDOWN_SPEED_INCREASE 1.0
#define LEVEL_6_TO_10_COUNTDOWN_SPEED_INCREASE 0.3
#define LEVEL_11_TO_20_COUNTDOWN_SPEED_INCREASE 0.2
#define LEVEL_21_ONWARDS_COUNTDOWN_SPEED_INCREASE 0.1
//increases
#define COUNTDOWN_HIGH_INCREASE_PERCENTAGE 48.0
#define COUNTDOWN_MEDIUM_INCREASE_PERCENTAGE 36.0
#define COUNTDOWN_LOW_INCREASE_PERCENTAGE 24.0
//animation
#define COUNTDOWN_BAR_GLOW_TIME 1.0
#define COUNTDOWN_WARNING_START_PERCENTAGE 30.0

//LEVEL
#define STARS_TO_LEVEL_UP 10
#define MAX_LEVEL 999

//SCORE
#define SCORE_FOR_HIGH_VALUE 375
#define SCORE_FOR_MEDIUM_VALUE 250
#define SCORE_FOR_LOW_VALUE 125
#define MAX_SCORE 999999

//COLOURS
#define STANDARD_PURPLE ccc3(160, 48, 252)
#define STANDARD_PINK
#define STANDARD_BLUE ccc3(3, 171, 255)
#define OPAQUE 255
#define TRANSPARENT 0

//FONTS
#define FONT_NAME @"Helvetica"
#define FONT_SIZE 19

//SOUNDS
#define SOUND_EFFECTS_ON_KEY @"soundEffectsOnKey"
#define MUSIC_ON_KEY @"musicOnKey"
#define FIRST_PLAY_KEY @"firstPlayKey"
#define SOUND_EFFECTS_VOLUME 0.2f
#define MUSIC_VOLUME 0.2f
#define SILENT 0.0

//MISC
#define GAME_LAYER_TAG 1
#define HIGH_SCORE_CATEGORY @"1"
#define APPLE_ID @"608072046"
#define FOUR_INCH_SCREEN_HEIGHT_ADJUSTMENT 44

#endif
